<a href="https://colab.research.google.com/github/shimjide123/datman/blob/main/PS3_by_Yu_Nong.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [133]:
import pandas as pd
import pandas_datareader as pdr
from pandas_datareader import wb
from pandas.io.formats.style import Styler
#s4 = Styler(df4, uuid_len=0, cell_ids=False)

from google.colab import files

In [134]:
import numpy as np

# Problem set 3

##First project:

exploring the way child marriage affect children and youth's completion of education, as well as correlaton of level of child and youth education, the frequencies of violence/terrorist/extremist activties, and the use of child labor. Given the definition of international Labor Organization (ILO) that recruiting children and youth into armed conflict is the worst form of child labour. So 4 datasets are used.

### data cleaning of 1st Dataset: Marrgage rates of children by country

In [135]:
Marriage=pd.read_excel('https://github.com/shimjide123/datman/raw/main/UNICEF%20Child-marriage-database.xlsx')

In [136]:
Marriage

,Countries and areas,Child marriage (%),Unnamed: 2,Unnamed: 3
0,NaN,NaN,NaN,NaN
1,NaN,Female Married by 15 (%),Female Married by 18 (%),Male Married by 18 (%)
2,NaN,NaN,NaN,NaN
3,Afghanistan,4.201,28.257,7.3
4,Albania,1.387,11.761,1.2
...,...,...,...,...
232,NaN,NaN,NaN,NaN
233,Source:,"UNICEF global databases, 2023, based on DHS, M...",NaN,NaN
234,NaN,NaN,NaN,NaN
235,Prepared by the Data and Analytics Section; Di...,NaN,NaN,NaN
236,Contact us:,data@unicef.org,NaN,NaN

In [137]:
Marriage.head()

,Countries and areas,Child marriage (%),Unnamed: 2,Unnamed: 3
0,NaN,NaN,NaN,NaN
1,NaN,Female Married by 15 (%),Female Married by 18 (%),Male Married by 18 (%)
2,NaN,NaN,NaN,NaN
3,Afghanistan,4.201,28.257,7.3
4,Albania,1.387,11.761,1.2

In [138]:
Marriage.rename(columns={'Child marriage (%)': 'Female_married_by_15(%)'}, inplace=True)
Marriage.rename(columns={'Unnamed: 2': 'Female_married_by_18(%)'}, inplace=True)
Marriage.rename(columns={'Unnamed: 3': 'Male_married_by_18(%)'}, inplace=True)
Marriage.rename(columns={'Countries and areas': 'Countries'}, inplace=True)

In [139]:
Marriage['Female_married_by_18(%)'] = pd.to_numeric(Marriage['Female_married_by_18(%)'], errors='coerce')
Marriage['Female_married_by_15(%)'] = pd.to_numeric(Marriage['Female_married_by_15(%)'], errors='coerce')
Marriage['Male_married_by_18(%)'] = pd.to_numeric(Marriage['Male_married_by_18(%)'], errors='coerce')

In [140]:
Marriage.dtypes

Countries                   object
Female_married_by_15(%)    float64
Female_married_by_18(%)    float64
Male_married_by_18(%)      float64
dtype: object

In [141]:
Marriage.reset_index(drop=True)
Marriage.head()

,Countries,Female_married_by_15(%),Female_married_by_18(%),Male_married_by_18(%)
0,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN
3,Afghanistan,4.201,28.257,7.3
4,Albania,1.387,11.761,1.2

In [142]:
Marriage=Marriage.fillna('') #a command of cleaning up the "NaN" values #aok no NaN is a python code for missing
Marriage.head()

,Countries,Female_married_by_15(%),Female_married_by_18(%),Male_married_by_18(%)
0,,,,
1,,,,
2,,,,
3,Afghanistan,4.201,28.257,7.3
4,Albania,1.387,11.761,1.2

In [143]:
#Since the first 3 rows are empty, I will drop it
Marriage=Marriage.drop(Marriage.index[[0,1,2]],axis=0)

In [144]:
Marriage.reset_index(drop=True) #reorder the indexes

,Countries,Female_married_by_15(%),Female_married_by_18(%),Male_married_by_18(%)
0,Afghanistan,4.201,28.257,7.3
1,Albania,1.387,11.761,1.2
2,Algeria,0.0,3.8,
3,Andorra,,,
4,Angola,7.902,30.331,6.0
...,...,...,...,...
229,,,,
230,Source:,,,
231,,,,
232,Prepared by the Data and Analytics Section; Di...,,,
233,Contact us:,,,

In [145]:
#according to the original file, Eastern & Southern Africa and West & Central Africa fall under the category of Sub-saharan Africa, and Eastern Europe & Central Asia and Western Europe fall under the category of Europe & Central Asia. Thus i dropped these 4 rows due to repetition.
Marriage=Marriage.drop([209,210,216,217])

In [205]:
Marriage.head()

,Countries,Female_married_by_15(%),Female_married_by_18(%),Male_married_by_18(%)
3,Afghanistan,4.201,28.257,7.3
4,Albania,1.387,11.761,1.2
5,Algeria,0.0,3.8,
6,Andorra,,,
7,Angola,7.902,30.331,6.0

###data cleaning of 2nd dataset: percentage of children and youth completing their education at school.

the link is:https://data.unicef.org/topic/education/overview/

In [147]:
Completion=pd.read_excel('https://github.com/shimjide123/datman/raw/main/Completion_rate_2022_formatted%20(1).xlsx')

In [148]:
Completion.head()

,Countries,Regions,Development Regions,Total,Female_completion_rate,Male_completion_rate,Rural_completion_rate,Urban_completion_rate,female_population,male_population,Urban_percentage
0,Afghanistan,SA,Least Developed,22.895340,14.365360,32.315559,16.607441,38.913071,1380667.0,1458082.0,0.254949
1,Albania,ECA,More Developed,77.947960,79.857063,76.226807,69.100288,83.281387,53510.0,61841.0,0.603189
2,Algeria,MENA,Less Developed,46.431679,59.164452,34.630589,35.473091,52.634720,878622.0,914222.0,0.726290
3,Andorra,ECA,More Developed,NaN,NaN,NaN,NaN,NaN,665.0,713.0,0.880615
4,Angola,SSA,Least Developed,18.743900,15.210190,23.698139,3.587311,24.791439,1160585.0,1143853.0,0.655144

In [149]:
#in this step, I will clean the dataset by removing the "NaN".
Completion=Completion.fillna('')
Completion.head()

,Countries,Regions,Development Regions,Total,Female_completion_rate,Male_completion_rate,Rural_completion_rate,Urban_completion_rate,female_population,male_population,Urban_percentage
0,Afghanistan,SA,Least Developed,22.89534,14.36536,32.315559,16.607441,38.913071,1380667.0,1458082.0,0.254949
1,Albania,ECA,More Developed,77.94796,79.857063,76.226807,69.100288,83.281387,53510.0,61841.0,0.603189
2,Algeria,MENA,Less Developed,46.431679,59.164452,34.630589,35.473091,52.63472,878622.0,914222.0,0.72629
3,Andorra,ECA,More Developed,,,,,,665.0,713.0,0.880615
4,Angola,SSA,Least Developed,18.7439,15.21019,23.698139,3.587311,24.791439,1160585.0,1143853.0,0.655144

In [150]:
Completion.dtypes

Countries                 object
Regions                   object
Development Regions       object
Total                     object
Female_completion_rate    object
Male_completion_rate      object
Rural_completion_rate     object
Urban_completion_rate     object
 female_population        object
male_population           object
Urban_percentage          object
dtype: object

In [151]:
Completion=Completion.fillna('')
Completion.head(250)

,Countries,Regions,Development Regions,Total,Female_completion_rate,Male_completion_rate,Rural_completion_rate,Urban_completion_rate,female_population,male_population,Urban_percentage
0,Afghanistan,SA,Least Developed,22.89534,14.36536,32.315559,16.607441,38.913071,1380667.0,1458082.0,0.254949
1,Albania,ECA,More Developed,77.94796,79.857063,76.226807,69.100288,83.281387,53510.0,61841.0,0.603189
2,Algeria,MENA,Less Developed,46.431679,59.164452,34.630589,35.473091,52.63472,878622.0,914222.0,0.72629
3,Andorra,ECA,More Developed,,,,,,665.0,713.0,0.880615
4,Angola,SSA,Least Developed,18.7439,15.21019,23.698139,3.587311,24.791439,1160585.0,1143853.0,0.655144
...,...,...,...,...,...,...,...,...,...,...,...
214,Sub-Saharan Africa,SSA,,,,,,,,,
215,Eastern & Southern Africa,,,,,,,,,,
216,West & Central Africa,,,,,,,,,,
217,Least developed countries,,LDC,,,,,,,,
218,World,,,,,,,,,,

In [152]:
#according to the original file, Eastern & Southern Africa and West & Central Africa fall under the category of Sub-saharan Africa, and Eastern Europe & Central Asia and Western Europe fall under the category of Europe & Central Asia. Thus i dropped these 4 rows due to repetition.
Completion=Completion.drop([208,209,215,216])

In [153]:
Completion.head(220)

,Countries,Regions,Development Regions,Total,Female_completion_rate,Male_completion_rate,Rural_completion_rate,Urban_completion_rate,female_population,male_population,Urban_percentage
0,Afghanistan,SA,Least Developed,22.89534,14.36536,32.315559,16.607441,38.913071,1380667.0,1458082.0,0.254949
1,Albania,ECA,More Developed,77.94796,79.857063,76.226807,69.100288,83.281387,53510.0,61841.0,0.603189
2,Algeria,MENA,Less Developed,46.431679,59.164452,34.630589,35.473091,52.63472,878622.0,914222.0,0.72629
3,Andorra,ECA,More Developed,,,,,,665.0,713.0,0.880615
4,Angola,SSA,Least Developed,18.7439,15.21019,23.698139,3.587311,24.791439,1160585.0,1143853.0,0.655144
...,...,...,...,...,...,...,...,...,...,...,...
212,North America,,,,,,,,,,
213,South Asia,SA,,,,,,,,,
214,Sub-Saharan Africa,SSA,,,,,,,,,
217,Least developed countries,,LDC,,,,,,,,
218,World,,,,,,,,,,

### 1st Merge: the 1st and the 2nd datasets

In [154]:
Marriage_Completion = pd.merge(Marriage, Completion, how='outer', on=['Countries'],indicator=True) #outer=keep all
Marriage_Completion #.head(131)
#aok aha! mistake! turkey should have merged!!
# so need to replace on condition:
#auto.loc[auto['foreign'] =='Domestic', 'colOfOnes']  = '100'

,Countries,Female_married_by_15(%),Female_married_by_18(%),Male_married_by_18(%),Regions,Development Regions,Total,Female_completion_rate,Male_completion_rate,Rural_completion_rate,Urban_completion_rate,female_population,male_population,Urban_percentage,_merge
0,Afghanistan,4.201,28.257,7.3,SA,Least Developed,22.89534,14.36536,32.315559,16.607441,38.913071,1380667.0,1458082.0,0.254949,both
1,Albania,1.387,11.761,1.2,ECA,More Developed,77.94796,79.857063,76.226807,69.100288,83.281387,53510.0,61841.0,0.603189,both
2,Algeria,0.0,3.8,,MENA,Less Developed,46.431679,59.164452,34.630589,35.473091,52.63472,878622.0,914222.0,0.72629,both
3,Andorra,,,,ECA,More Developed,,,,,,665.0,713.0,0.880615,both
4,Angola,7.902,30.331,6.0,SSA,Least Developed,18.7439,15.21019,23.698139,3.587311,24.791439,1160585.0,1143853.0,0.655144,both
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
246,Population coverage,NaN,NaN,NaN,,,,,,,,,,,right_only
247,East Asia & Pacific,NaN,NaN,NaN,EAP,,,,,,,,,,right_only
248,Europe & Central Asia,NaN,NaN,NaN,ECA,,,,,,,,,,right_only
249,Latin America & Caribbean,NaN,NaN,NaN,LAC,,,,,,,,,,right_only
250,Middle East & North Africa,NaN,NaN,NaN,MENA,,,,,,,,,,right_only

In [155]:
order=['Countries','Regions','Development Regions','Female_married_by_15(%)','Female_married_by_18(%)','Male_married_by_18(%)','Total','Female_completion_rate', 'Male_completion_rate','Rural_completion_rate','Urban_completion_rate','Urban_percentage',	'_merge']

In [156]:
Marriage_Completion=Marriage_Completion[order]
Marriage_Completion.head()

,Countries,Regions,Development Regions,Female_married_by_15(%),Female_married_by_18(%),Male_married_by_18(%),Total,Female_completion_rate,Male_completion_rate,Rural_completion_rate,Urban_completion_rate,Urban_percentage,_merge
0,Afghanistan,SA,Least Developed,4.201,28.257,7.3,22.89534,14.36536,32.315559,16.607441,38.913071,0.254949,both
1,Albania,ECA,More Developed,1.387,11.761,1.2,77.94796,79.857063,76.226807,69.100288,83.281387,0.603189,both
2,Algeria,MENA,Less Developed,0.0,3.8,,46.431679,59.164452,34.630589,35.473091,52.63472,0.72629,both
3,Andorra,ECA,More Developed,,,,,,,,,0.880615,both
4,Angola,SSA,Least Developed,7.902,30.331,6.0,18.7439,15.21019,23.698139,3.587311,24.791439,0.655144,both

In [157]:
Marriage_Completion.dtypes

Countries                    object
Regions                      object
Development Regions          object
Female_married_by_15(%)      object
Female_married_by_18(%)      object
Male_married_by_18(%)        object
Total                        object
Female_completion_rate       object
Male_completion_rate         object
Rural_completion_rate        object
Urban_completion_rate        object
Urban_percentage             object
_merge                     category
dtype: object

In [158]:
Marriage_Completion['Total'] = pd.to_numeric(Marriage_Completion['Total'], errors='coerce')
Marriage_Completion['Female_completion_rate'] = pd.to_numeric(Marriage_Completion['Female_completion_rate'], errors='coerce')
Marriage_Completion['Male_completion_rate'] = pd.to_numeric(Marriage_Completion['Male_completion_rate'], errors='coerce')
Marriage_Completion['Rural_completion_rate'] = pd.to_numeric(Marriage_Completion['Rural_completion_rate'], errors='coerce')
Marriage_Completion['Urban_completion_rate'] = pd.to_numeric(Marriage_Completion['Urban_completion_rate'], errors='coerce')
Marriage_Completion['Urban_percentage'] = pd.to_numeric(Marriage_Completion['Urban_percentage'], errors='coerce')
Marriage_Completion['Female_married_by_15(%)'] = pd.to_numeric(Marriage_Completion['Female_married_by_15(%)'], errors='coerce')
Marriage_Completion['Female_married_by_18(%)'] = pd.to_numeric(Marriage_Completion['Female_married_by_15(%)'], errors='coerce')
Marriage_Completion['Male_married_by_18(%)'] = pd.to_numeric(Marriage_Completion['Female_married_by_15(%)'], errors='coerce')

<ipython-input-158-e70c34c63aa7>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Marriage_Completion['Total'] = pd.to_numeric(Marriage_Completion['Total'], errors='coerce')
<ipython-input-158-e70c34c63aa7>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Marriage_Completion['Female_completion_rate'] = pd.to_numeric(Marriage_Completion['Female_completion_rate'], errors='coerce')
<ipython-input-158-e70c34c63aa7>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Marriage_Completion['Male_completion_rate'] = pd.to_numeric(Marriage_Completion['Male_completion_rate'], errors='coerce')
<ipython-input-158-e70c34c63aa7>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Marriage_Completion['Rural_completion_rate'] = pd.to_numeric(Marriage_Completion['Rural_completion_rate'], errors='coerce')
<ipython-input-158-e70c34c63aa7>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Marriage_Completion['Urban_completion_rate'] = pd.to_numeric(Marriage_Completion['Urban_completion_rate'], errors='coerce')
<ipython-input-158-e70c34c63aa7>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Marriage_Completion['Urban_percentage'] = pd.to_numeric(Marriage_Completion['Urban_percentage'], errors='coerce')
<ipython-input-158-e70c34c63aa7>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Marriage_Completion['Female_married_by_15(%)'] = pd.to_numeric(Marriage_Completion['Female_married_by_15(%)'], errors='coerce')
<ipython-input-158-e70c34c63aa7>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Marriage_Completion['Female_married_by_18(%)'] = pd.to_numeric(Marriage_Completion['Female_married_by_15(%)'], errors='coerce')
<ipython-input-158-e70c34c63aa7>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Marriage_Completion['Male_married_by_18(%)'] = pd.to_numeric(Marriage_Completion['Female_married_by_15(%)'], errors='coerce')

In [159]:
Marriage_Completion['_merge'].value_counts() #.plot(kind='barh')

both          231
left_only      12
right_only      8
Name: _merge, dtype: int64

In [160]:
Marriage_Completion['Countries'][Marriage_Completion['_merge']=='left_only']

126                         Netherlands (Kingdom of the)
184                                              Türkiye
228                                              SUMMARY
229                                East Asia and Pacific
230                              Europe and Central Asia
231                          Latin America and Caribbean
232                         Middle East and North Africa
238                                               Notes:
239                               Indicator definitions:
240                                             Source:
241    Prepared by the Data and Analytics Section; Di...
242                                        Contact us:
Name: Countries, dtype: object

In [161]:
Marriage_Completion['Countries'][Marriage_Completion['_merge']=='right_only']

243    Kosovo under UNSC res. 1244*
244                     Netherlands
245                          Turkey
246             Population coverage
247             East Asia & Pacific
248           Europe & Central Asia
249       Latin America & Caribbean
250      Middle East & North Africa
Name: Countries, dtype: object

In [162]:
Marriage_Completion.query("_merge=='left_only'")
# Bug identified: Netherlands (Kingdom) and Turkiye do not merge with Netherland and Turkey in the "right_only". Will fix it with replace on conditions.

,Countries,Regions,Development Regions,Female_married_by_15(%),Female_married_by_18(%),Male_married_by_18(%),Total,Female_completion_rate,Male_completion_rate,Rural_completion_rate,Urban_completion_rate,Urban_percentage,_merge
126,Netherlands (Kingdom of the),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
184,Türkiye,NaN,NaN,2.000,2.000,2.000,NaN,NaN,NaN,NaN,NaN,NaN,left_only
228,SUMMARY,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
229,East Asia and Pacific,NaN,NaN,0.935,0.935,0.935,NaN,NaN,NaN,NaN,NaN,NaN,left_only
230,Europe and Central Asia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
231,Latin America and Caribbean,NaN,NaN,3.993,3.993,3.993,NaN,NaN,NaN,NaN,NaN,NaN,left_only
232,Middle East and North Africa,NaN,NaN,2.385,2.385,2.385,NaN,NaN,NaN,NaN,NaN,NaN,left_only
238,Notes:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
239,Indicator definitions:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
240,Source:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
241,Prepared by the Data and Analytics Section; Di...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
242,Contact us:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only

In [163]:
Marriage_Completion.query("_merge=='right_only'")
#Bug identified: Netherland and Turkey do not merge with Netherlands (Kingdom) and Turkiye in the "left_only". Will fix it with replace on conditions in the next step.

,Countries,Regions,Development Regions,Female_married_by_15(%),Female_married_by_18(%),Male_married_by_18(%),Total,Female_completion_rate,Male_completion_rate,Rural_completion_rate,Urban_completion_rate,Urban_percentage,_merge
243,Kosovo under UNSC res. 1244*,ECA,,NaN,NaN,NaN,87.20000,86.600000,87.900000,85.20000,90.200000,NaN,right_only
244,Netherlands,ECA,More Developed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.914901,right_only
245,Turkey,ECA,Less Developed,NaN,NaN,NaN,47.49535,43.577709,51.190842,26.00873,52.064159,0.751429,right_only
246,Population coverage,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,right_only
247,East Asia & Pacific,EAP,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,right_only
248,Europe & Central Asia,ECA,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,right_only
249,Latin America & Caribbean,LAC,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,right_only
250,Middle East & North Africa,MENA,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,right_only

In [164]:
Marriage.loc[Marriage['Countries']=='Türkiye','Countries']='Turkey'
Marriage.loc[Marriage['Countries']=='Netherlands (Kingdom of the)','Countries']='Netherlands'
Completion.loc[Completion['Countries']=='Kosovo under UNSC res. 1244*','Countries']='Kosovo'

In [165]:
Completion.loc[Completion['Countries']=='East Asia & Pacific','Countries']='East Asia and Pacific'
Completion.loc[Completion['Countries']=='Europe & Central Asia','Countries']='Europe and Central Asia'
Completion.loc[Completion['Countries']=='Latin America & Caribbean','Countries']='Latin America and Caribbean'
Completion.loc[Completion['Countries']=='Middle East & North Africa','Countries']='Middle East and North Africa'

In [166]:
Completion.head (210)

,Countries,Regions,Development Regions,Total,Female_completion_rate,Male_completion_rate,Rural_completion_rate,Urban_completion_rate,female_population,male_population,Urban_percentage
0,Afghanistan,SA,Least Developed,22.89534,14.36536,32.315559,16.607441,38.913071,1380667.0,1458082.0,0.254949
1,Albania,ECA,More Developed,77.94796,79.857063,76.226807,69.100288,83.281387,53510.0,61841.0,0.603189
2,Algeria,MENA,Less Developed,46.431679,59.164452,34.630589,35.473091,52.63472,878622.0,914222.0,0.72629
3,Andorra,ECA,More Developed,,,,,,665.0,713.0,0.880615
4,Angola,SSA,Least Developed,18.7439,15.21019,23.698139,3.587311,24.791439,1160585.0,1143853.0,0.655144
...,...,...,...,...,...,...,...,...,...,...,...
205,Population coverage,,,,,,,,,,
206,East Asia and Pacific,EAP,,,,,,,,,
207,Europe and Central Asia,ECA,,,,,,,,,
210,Latin America and Caribbean,LAC,,,,,,,,,
211,Middle East and North Africa,MENA,,,,,,,,,

In [167]:
#it is time to remerge the 2 datasets, after replace on conditon
RevisedMarriage_Completion = pd.merge(Marriage, Completion, how='outer', on=['Countries'],indicator=True)

In [168]:
RevisedMarriage_Completion['_merge'].value_counts()

both          237
left_only       6
right_only      2
Name: _merge, dtype: int64

In [169]:
RevisedMarriage_Completion.query("_merge=='left_only'")

,Countries,Female_married_by_15(%),Female_married_by_18(%),Male_married_by_18(%),Regions,Development Regions,Total,Female_completion_rate,Male_completion_rate,Rural_completion_rate,Urban_completion_rate,female_population,male_population,Urban_percentage,_merge
228,SUMMARY,,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
238,Notes:,,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
239,Indicator definitions:,,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
240,Source:,,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
241,Prepared by the Data and Analytics Section; Di...,,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
242,Contact us:,,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only

In [170]:
RevisedMarriage_Completion.query("_merge=='right_only'") #the values of kosovo only is in the dataset of education completion rate.

,Countries,Female_married_by_15(%),Female_married_by_18(%),Male_married_by_18(%),Regions,Development Regions,Total,Female_completion_rate,Male_completion_rate,Rural_completion_rate,Urban_completion_rate,female_population,male_population,Urban_percentage,_merge
243,Kosovo,NaN,NaN,NaN,ECA,,87.2,86.6,87.9,85.2,90.2,,,,right_only
244,Population coverage,NaN,NaN,NaN,,,,,,,,,,,right_only

###2nd merge with the 3rd dataset: the percentage of child labor by country.
link is: https://data.unicef.org/topic/child-protection/child-labour/

In [171]:
labor=pd.read_excel('https://github.com/shimjide123/datman/raw/main/XLS_Child-labour-database_June-2023%20(1).xlsx')

In [172]:
display(RevisedMarriage_Completion, labor)

,Countries,Female_married_by_15(%),Female_married_by_18(%),Male_married_by_18(%),Regions,Development Regions,Total,Female_completion_rate,Male_completion_rate,Rural_completion_rate,Urban_completion_rate,female_population,male_population,Urban_percentage,_merge
0,Afghanistan,4.201,28.257,7.3,SA,Least Developed,22.89534,14.36536,32.315559,16.607441,38.913071,1380667.0,1458082.0,0.254949,both
1,Albania,1.387,11.761,1.2,ECA,More Developed,77.94796,79.857063,76.226807,69.100288,83.281387,53510.0,61841.0,0.603189,both
2,Algeria,0.0,3.8,,MENA,Less Developed,46.431679,59.164452,34.630589,35.473091,52.63472,878622.0,914222.0,0.72629,both
3,Andorra,,,,ECA,More Developed,,,,,,665.0,713.0,0.880615,both
4,Angola,7.902,30.331,6.0,SSA,Least Developed,18.7439,15.21019,23.698139,3.587311,24.791439,1160585.0,1143853.0,0.655144,both
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
240,Source:,,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
241,Prepared by the Data and Analytics Section; Di...,,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
242,Contact us:,,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
243,Kosovo,NaN,NaN,NaN,ECA,,87.2,86.6,87.9,85.2,90.2,,,,right_only
244,Population coverage,NaN,NaN,NaN,,,,,,,,,,,right_only

,Countries,Total_Child_labor,Male_Child_labor,Female_Child_labor
0,Afghanistan,13,14.2,11.7
1,Albania,3.3,3.6,3
2,Algeria,2.5,2.9,2
3,Andorra,-,-,-
4,Angola,18.724,16.6,19.87
...,...,...,...,...
197,Venezuela (Bolivarian Republic of),-,-,-
198,Viet Nam,6.94,6.359,7.555
199,Yemen,-,-,-
200,Zambia,23,22.9,23
201,Zimbabwe,27.9,33.1,22.4

In [173]:
RevisedMarriage_Completion=RevisedMarriage_Completion.drop(columns=['_merge'])

In [174]:
marriage_completion_labor=pd.merge(RevisedMarriage_Completion, labor,how='outer',indicator=True, on='Countries')
#here I merge the datasets of child labor rate, child marriage rate, and the rate of school completion.

In [175]:
marriage_completion_labor['_merge'].value_counts()

both          200
left_only      45
right_only      2
Name: _merge, dtype: int64

In [176]:
marriage_completion_labor.query("_merge=='right_only'")

,Countries,Female_married_by_15(%),Female_married_by_18(%),Male_married_by_18(%),Regions,Development Regions,Total,Female_completion_rate,Male_completion_rate,Rural_completion_rate,Urban_completion_rate,female_population,male_population,Urban_percentage,Total_Child_labor,Male_Child_labor,Female_Child_labor,_merge
245,Netherlands (Kingdom of the),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-,-,-,right_only
246,Türkiye,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.831,4.073,3.577,right_only

In [177]:
labor.loc[labor['Countries']=='Netherlands (Kingdom of the)','Countries']='Netherlands'
labor.loc[labor['Countries']=='Türkiye','Countries']='Turkey'
labor.head(187)

,Countries,Total_Child_labor,Male_Child_labor,Female_Child_labor
0,Afghanistan,13,14.2,11.7
1,Albania,3.3,3.6,3
2,Algeria,2.5,2.9,2
3,Andorra,-,-,-
4,Angola,18.724,16.6,19.87
...,...,...,...,...
182,Trinidad and Tobago,0.76,0.722,0.799
183,Tunisia,2.255,3.02,1.439
184,Turkey,3.831,4.073,3.577
185,Turkmenistan,0.281,0.43,0.12
186,Turks and Caicos Islands,6.1,8.7,2.9

In [178]:
marriage_completion_labor=pd.merge(RevisedMarriage_Completion, labor,how='outer',indicator=True, on='Countries')

In [179]:
marriage_completion_labor['_merge'].value_counts()

both          202
left_only      43
right_only      0
Name: _merge, dtype: int64

In [180]:
marriage_completion_labor.query("_merge=='left_only'") #so, the left_only obs are either empty rows, or obs that only contain values from a part of the datasets

,Countries,Female_married_by_15(%),Female_married_by_18(%),Male_married_by_18(%),Regions,Development Regions,Total,Female_completion_rate,Male_completion_rate,Rural_completion_rate,Urban_completion_rate,female_population,male_population,Urban_percentage,Total_Child_labor,Male_Child_labor,Female_Child_labor,_merge
202,,,,,,,,,,,,,,,NaN,NaN,NaN,left_only
203,,,,,,,,,,,,,,,NaN,NaN,NaN,left_only
204,,,,,,,,,,,,,,,NaN,NaN,NaN,left_only
205,,,,,,,,,,,,,,,NaN,NaN,NaN,left_only
206,,,,,,,,,,,,,,,NaN,NaN,NaN,left_only
207,,,,,,,,,,,,,,,NaN,NaN,NaN,left_only
208,,,,,,,,,,,,,,,NaN,NaN,NaN,left_only
209,,,,,,,,,,,,,,,NaN,NaN,NaN,left_only
210,,,,,,,,,,,,,,,NaN,NaN,NaN,left_only
211,,,,,,,,,,,,,,,NaN,NaN,NaN,left_only
212,,,,,,,,,,,,,,,NaN,NaN,NaN,left_only
213,,,,,,,,,,,,,,,NaN,NaN,NaN,left_only
214,,,,,,,,,,,,,,,NaN,NaN,NaN,left_only
215,,,,,,,,,,,,,,,NaN,NaN,NaN,left_only
216,,,,,,,,,,,,,,,NaN,NaN,NaN,left_only
217,,,,,,,,,,,,,,,NaN,NaN,NaN,left_only
218,,,,,,,,,,,,,,,NaN,NaN,NaN,left_only
219,,,,,,,,,,,,,,,NaN,NaN,NaN,left_only
220,,,,,,,,,,,,,,,NaN,NaN,NaN,left_only
221,,,,,,,,,,,,,,,NaN,NaN,NaN,left_only
222,,,,,,,,,,,,,,,NaN,NaN,NaN,left_only
223,,,,,,,,,,,,,,,NaN,NaN,NaN,left_only
224,,,,,,,,,,,,,,,NaN,NaN,NaN,left_only
225,,,,,,,,,,,,,,,NaN,NaN,NaN,left_only
226,,,,,,,,,,,,,,,NaN,NaN,NaN,left_only
227,,,,,,,,,,,,,,,NaN,NaN,NaN,left_only
228,SUMMARY,,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
229,East Asia and Pacific,0.935,8.248,1.373,EAP,,,,,,,,,,NaN,NaN,NaN,left_only
230,Europe and Central Asia,,7.031,,ECA,,,,,,,,,,NaN,NaN,NaN,left_only
231,Latin America and Caribbean,3.993,21.237,,LAC,,,,,,,,,,NaN,NaN,NaN,left_only
232,Middle East and North Africa,2.385,15.757,,MENA,,,,,,,,,,NaN,NaN,NaN,left_only
233,North America,,,,,,,,,,,,,,NaN,NaN,NaN,left_only
234,South Asia,5.682,25.526,3.158,SA,,,,,,,,,,NaN,NaN,NaN,left_only
235,Sub-Saharan Africa,9.922,32.389,3.976,SSA,,,,,,,,,,NaN,NaN,NaN,left_only
236,Least developed countries,10.356,37.146,5.424,,LDC,,,,,,,,,NaN,NaN,NaN,left_only
237,World,4.24,18.675,2.819,,,,,,,,,,,NaN,NaN,NaN,left_only
238,Notes:,,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
239,Indicator definitions:,,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
240,Source:,,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
241,Prepared by the Data and Analytics Section; Di...,,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
242,Contact us:,,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
243,Kosovo,NaN,NaN,NaN,ECA,,87.2,86.6,87.9,85.2,90.2,,,,NaN,NaN,NaN,left_only
244,Population coverage,NaN,NaN,NaN,,,,,,,,,,,NaN,NaN,NaN,left_only

### 3rd merge with the 4th dataset: the freqencies of violence/terrorist activities by country, by merging this data,
I hope to explore the correlation of education completion rate and the activeness of social unrest.
lack of education opportunity may somewhat drive up conflict, because people without education are excluded from decent work, in this case participanting in conflict may be seen as the last resort.
children lacking education opportunitites are likely used in armed conflict, which is also a form of child labor according to International labor organization (ILO).

the link is: https://www.visionofhumanity.org/public-release-data/

In [181]:
Violence=pd.read_excel("https://github.com/shimjide123/datman/raw/main/GTI-2023-Overall-scores-2011-2022.xlsx")

In [182]:
Violence.head()

        Country  Rank     Score  Incidents  Fatalities  Injuries  Hostages
0   Afghanistan     1  8.822244        225         633       897         0
1  Burkina Faso     2  8.564101        310        1135       496        84
2       Somalia     3  8.463031        299         755      1001         0
3          Mali     4  8.412392        272         944       376        24
4         Syria     5  8.161243        197         447       451         2

In [183]:
Violence.rename(columns={'Country': 'Countries'}, inplace=True) #rename the 'Country' into 'Countries' to match when merging

In [184]:
Marriage_completion_labor=marriage_completion_labor.drop(columns=['_merge']) #dropping the _merge column so as to merge the 3nd dataset

In [185]:
#let's merge
Marriage_Completion_labor_Violence=pd.merge(Marriage_completion_labor,Violence, how='outer',indicator=True, on='Countries')

In [186]:
Marriage_Completion_labor_Violence.head()

,Countries,Female_married_by_15(%),Female_married_by_18(%),Male_married_by_18(%),Regions,Development Regions,Total,Female_completion_rate,Male_completion_rate,Rural_completion_rate,...,Total_Child_labor,Male_Child_labor,Female_Child_labor,Rank,Score,Incidents,Fatalities,Injuries,Hostages,_merge
0,Afghanistan,4.201,28.257,7.3,SA,Least Developed,22.89534,14.36536,32.315559,16.607441,...,13,14.2,11.7,1.0,8.822244,225.0,633.0,897.0,0.0,both
1,Albania,1.387,11.761,1.2,ECA,More Developed,77.94796,79.857063,76.226807,69.100288,...,3.3,3.6,3,93.0,0.000000,0.0,0.0,0.0,0.0,both
2,Algeria,0.0,3.8,,MENA,Less Developed,46.431679,59.164452,34.630589,35.473091,...,2.5,2.9,2,37.0,4.082835,1.0,3.0,0.0,0.0,both
3,Andorra,,,,ECA,More Developed,,,,,...,-,-,-,NaN,NaN,NaN,NaN,NaN,NaN,left_only
4,Angola,7.902,30.331,6.0,SSA,Least Developed,18.7439,15.21019,23.698139,3.587311,...,18.724,16.6,19.87,90.0,0.157670,0.0,0.0,0.0,0.0,both

In [187]:
Marriage_Completion_labor_Violence['_merge'].value_counts() #.plot(kind='barh')

both          143
left_only     102
right_only     20
Name: _merge, dtype: int64

In [188]:
Marriage_Completion_labor_Violence.query("_merge=='left_only'")

,Countries,Female_married_by_15(%),Female_married_by_18(%),Male_married_by_18(%),Regions,Development Regions,Total,Female_completion_rate,Male_completion_rate,Rural_completion_rate,...,Total_Child_labor,Male_Child_labor,Female_Child_labor,Rank,Score,Incidents,Fatalities,Injuries,Hostages,_merge
3,Andorra,,,,ECA,More Developed,,,,,...,-,-,-,NaN,NaN,NaN,NaN,NaN,NaN,left_only
5,Anguilla,,,,LAC,Not Classified,,,,,...,-,-,-,NaN,NaN,NaN,NaN,NaN,NaN,left_only
6,Antigua and Barbuda,,,,LAC,Less Developed,,,,,...,-,-,-,NaN,NaN,NaN,NaN,NaN,NaN,left_only
12,Bahamas,,,,LAC,Less Developed,,,,,...,-,-,-,NaN,NaN,NaN,NaN,NaN,NaN,left_only
15,Barbados,7.735,29.246,,LAC,Less Developed,93.900002,96.900002,91.199997,97.099998,...,1.354,1.776,0.944,NaN,NaN,NaN,NaN,NaN,NaN,left_only
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
239,Indicator definitions:,,,,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
240,Source:,,,,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
241,Prepared by the Data and Analytics Section; Di...,,,,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
242,Contact us:,,,,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
244,Population coverage,NaN,NaN,NaN,,,,,,,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only

Warning: Total number of columns (24) exceeds max_columns (20) limiting to first (20) columns.

In [189]:
Marriage_Completion_labor_Violence.query("_merge=='right_only'")

,Countries,Female_married_by_15(%),Female_married_by_18(%),Male_married_by_18(%),Regions,Development Regions,Total,Female_completion_rate,Male_completion_rate,Rural_completion_rate,...,Total_Child_labor,Male_Child_labor,Female_Child_labor,Rank,Score,Incidents,Fatalities,Injuries,Hostages,_merge
245,Syria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,5.0,8.161243,197.0,447.0,451.0,2.0,right_only
246,Iran,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,21.0,5.687521,7.0,42.0,68.0,0.0,right_only
247,United States of America,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,30.0,4.798798,8.0,11.0,7.0,0.0,right_only
248,Palestine,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,33.0,4.611276,17.0,1.0,21.0,0.0,right_only
249,Tanzania,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,38.0,4.064939,0.0,0.0,0.0,0.0,right_only
250,Russia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,45.0,3.799217,3.0,2.0,0.0,0.0,right_only
251,Cote d' Ivoire,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,47.0,3.747458,1.0,0.0,0.0,0.0,right_only
252,Venezuela,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,51.0,3.408650,0.0,0.0,0.0,0.0,right_only
253,Vietnam,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,89.0,0.226891,0.0,0.0,0.0,0.0,right_only
254,Czech Republic,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,93.0,0.000000,0.0,0.0,0.0,0.0,right_only
255,Taiwan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,93.0,0.000000,0.0,0.0,0.0,0.0,right_only
256,Bolivia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,93.0,0.000000,0.0,0.0,0.0,0.0,right_only
257,Republic of the Congo,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,93.0,0.000000,0.0,0.0,0.0,0.0,right_only
258,The Gambia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,93.0,0.000000,0.0,0.0,0.0,0.0,right_only
259,Kyrgyz Republic,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,93.0,0.000000,0.0,0.0,0.0,0.0,right_only
260,South Korea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,93.0,0.000000,0.0,0.0,0.0,0.0,right_only
261,Laos,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,93.0,0.000000,0.0,0.0,0.0,0.0,right_only
262,Moldova,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,93.0,0.000000,0.0,0.0,0.0,0.0,right_only
263,Macedonia (FYR),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,93.0,0.000000,0.0,0.0,0.0,0.0,right_only
264,North Korea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,93.0,0.000000,0.0,0.0,0.0,0.0,right_only

In [206]:
Violence.loc[Violence['Countries']=='Syria','Countries']='Syrian Arab Republic'
Violence.loc[Violence['Countries']=='United States of America','Countries']='United States'
Violence.loc[Violence['Countries']=='Russia','Countries']='Russian Federation'
Violence.loc[Violence['Countries']=='Iran','Countries']='Iran (Islamic Republic of)'
Violence.loc[Violence['Countries']=='Laos','Countries']="Lao People's Democratic Republic"
Violence.loc[Violence['Countries']=='South Korea','Countries']='Republic of Korea'
Violence.loc[Violence['Countries']=='North Korea','Countries']="Democratic People's Republic of Korea"
Violence.loc[Violence['Countries']=='Republic of the Congo','Countries']='Congo'
Violence.loc[Violence['Countries']=='Vietnam','Countries']="Viet Nam"
Violence.loc[Violence['Countries']=='Tanzania','Countries']='United Republic of Tanzania'
Violence.loc[Violence['Countries']=="Cote d' Ivoire",'Countries']="Côte d'Ivoire"
Violence.loc[Violence['Countries']=="Palestine",'Countries']="State of Palestine"
Violence.loc[Violence['Countries']=="The Gambia",'Countries']="Gambia"
Violence.loc[Violence['Countries']=="Venezuela",'Countries']="Venezuela (Bolivarian Republic of)"
Violence.loc[Violence['Countries']=="Bolivia",'Countries']="Bolivia (Plurinational State of)"
Violence.loc[Violence['Countries']=="Kyrgyz Republic",'Countries']="Kyrgyzstan"
Violence.loc[Violence['Countries']=="Czech Republic",'Countries']="Czechia"
Violence.loc[Violence['Countries']=="Macedonia (FYR)",'Countries']="North Macedonia"
Violence.loc[Violence['Countries']=="Moldova",'Countries']="Republic of Moldova"

In [207]:
Violence.head(253)

,Countries,Rank,Score,Incidents,Fatalities,Injuries,Hostages
0,Afghanistan,1,8.822244,225,633,897,0
1,Burkina Faso,2,8.564101,310,1135,496,84
2,Somalia,3,8.463031,299,755,1001,0
3,Mali,4,8.412392,272,944,376,24
4,Syrian Arab Republic,5,8.161243,197,447,451,2
...,...,...,...,...,...,...,...
158,Turkmenistan,93,0.000000,0,0,0,0
159,Timor-Leste,93,0.000000,0,0,0,0
160,Trinidad and Tobago,93,0.000000,0,0,0,0
161,Zambia,93,0.000000,0,0,0,0
162,Zimbabwe,93,0.000000,0,0,0,0

In [208]:
Marriage_Completion_labor_Violence=pd.merge(Marriage_completion_labor,Violence, how='outer',indicator=True, on='Countries')

In [209]:
Marriage_Completion_labor_Violence['_merge'].value_counts()

both          162
left_only      83
right_only      1
Name: _merge, dtype: int64

In [210]:
Marriage_Completion_labor_Violence.query("_merge=='right_only'")

,Countries,Female_married_by_15(%),Female_married_by_18(%),Male_married_by_18(%),Regions,Development Regions,Total,Female_completion_rate,Male_completion_rate,Rural_completion_rate,...,Total_Child_labor,Male_Child_labor,Female_Child_labor,Rank,Score,Incidents,Fatalities,Injuries,Hostages,_merge
245,Taiwan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,93.0,0.0,0.0,0.0,0.0,0.0,right_only

In [201]:
Marriage_Completion_labor_Violence=pd.merge(Marriage_completion_labor,Violence, how='inner',indicator=True, on='Countries')

In [202]:
Marriage_Completion_labor_Violence['_merge'].value_counts()

both          160
left_only       0
right_only      0
Name: _merge, dtype: int64

In [204]:
pd.crosstab(Marriage_Completion_labor_Violence["Countries"],Marriage_Completion_labor_Violence["_merge"])

_merge                              both
Countries
Afghanistan                            1
Albania                                1
Algeria                                1
Angola                                 1
Argentina                              1
...                                  ...
Venezuela (Bolivarian Republic of)     1
Viet Nam                               1
Yemen                                  1
Zambia                                 1
Zimbabwe                               1

[160 rows x 1 columns]

In [203]:
Marriage_Completion_labor_Violence=Marriage_Completion_labor_Violence.fillna('')
Marriage_Completion_labor_Violence.head()

,Countries,Female_married_by_15(%),Female_married_by_18(%),Male_married_by_18(%),Regions,Development Regions,Total,Female_completion_rate,Male_completion_rate,Rural_completion_rate,...,Total_Child_labor,Male_Child_labor,Female_Child_labor,Rank,Score,Incidents,Fatalities,Injuries,Hostages,_merge
0,Afghanistan,4.201,28.257,7.3,SA,Least Developed,22.89534,14.36536,32.315559,16.607441,...,13,14.2,11.7,1,8.822244,225,633,897,0,both
1,Albania,1.387,11.761,1.2,ECA,More Developed,77.94796,79.857063,76.226807,69.100288,...,3.3,3.6,3,93,0.000000,0,0,0,0,both
2,Algeria,0.0,3.8,,MENA,Less Developed,46.431679,59.164452,34.630589,35.473091,...,2.5,2.9,2,37,4.082835,1,3,0,0,both
3,Angola,7.902,30.331,6.0,SSA,Least Developed,18.7439,15.21019,23.698139,3.587311,...,18.724,16.6,19.87,90,0.157670,0,0,0,0,both
4,Argentina,2.386,15.45,,LAC,Less Developed,60.195518,65.963852,54.310711,,...,-,-,-,57,2.875466,4,0,2,0,both

##Second project:

exploring correlation between population displacement at the country level and the national risk on food, water, population and disaster, as well as how they affect the index of happiness.

###1st dataset for the second project: displaced population by country due to conflict and disaster.
Link to it: https://www.internal-displacement.org/database/displacement-data

In [218]:
displacement=pd.read_excel("https://github.com/shimjide123/datman/raw/main/IDMC_Internal_Displacement_Conflict-Violence_Disasters.xlsx")

In [219]:
displacement.head()

,ISO3,Name,Year,Conflict Stock Displacement,Conflict Stock Displacement (Raw),Conflict Internal Displacements,Conflict Internal Displacements (Raw),Disaster Internal Displacements,Disaster Internal Displacements (Raw),Disaster Stock Displacement,Disaster Stock Displacement (Raw)
0,AB9,Abyei Area,2022,56000.0,55705.0,56000.0,55705.0,29000.0,28803.0,NaN,NaN
1,AFG,Afghanistan,2022,4394000.0,4393749.0,32000.0,32424.0,220000.0,220387.0,2164000.0,2164085.0
2,AGO,Angola,2022,NaN,NaN,NaN,NaN,1800.0,1771.0,NaN,NaN
3,ALB,Albania,2022,NaN,NaN,NaN,NaN,320.0,318.0,NaN,NaN
4,ARG,Argentina,2022,NaN,NaN,NaN,NaN,730.0,731.0,NaN,NaN

In [220]:
displacement.rename(columns={'Name': 'Countries'}, inplace=True) #for the sake of merge

In [221]:
displacement.drop(columns=["ISO3","Conflict Stock Displacement (Raw)", "Conflict Internal Displacements (Raw)"],inplace=True) #these columus are no use

In [222]:
displacement.drop(columns=["Disaster Internal Displacements (Raw)", "Disaster Stock Displacement (Raw)"],inplace=True)
#dropping for the same reason, they are redundant.

In [223]:
displacement.head()

,Countries,Year,Conflict Stock Displacement,Conflict Internal Displacements,Disaster Internal Displacements,Disaster Stock Displacement
0,Abyei Area,2022,56000.0,56000.0,29000.0,NaN
1,Afghanistan,2022,4394000.0,32000.0,220000.0,2164000.0
2,Angola,2022,NaN,NaN,1800.0,NaN
3,Albania,2022,NaN,NaN,320.0,NaN
4,Argentina,2022,NaN,NaN,730.0,NaN

###2nd dataset for second project: Ecological threat indexs measuring the risks on food security, population growth, water shortage, and natural disaster.
the link is: https://www.visionofhumanity.org/public-release-data/

In [224]:
Ethreat=pd.read_excel("https://github.com/shimjide123/datman/raw/main/ETR_Public_Release_Data_2022.xlsx")

In [225]:
Ethreat.head()

,Country,Food Risk Score,Natural Disasters Score,Rapid Population Growth Score,Water Risk Score
0,Burundi,5,5,5,5
1,Central African Republic,5,5,5,5
2,Republic of the Congo,5,5,5,5
3,Kenya,5,5,5,5
4,Mozambique,5,5,5,5

In [226]:
Ethreat.rename(columns={'Country': 'Countries'}, inplace=True)

In [227]:
#merge the above 2 datasets first
Ethreat_displacement=pd.merge(Ethreat, displacement, how='outer', on=['Countries'],indicator=True) ##I use "inner" merge, keeping obs with both values of displacement and ecological threat only, as I only need to see how both types of values interact.

In [228]:
Ethreat_displacement['_merge'].value_counts()

both          135
left_only      93
right_only     18
Name: _merge, dtype: int64

In [233]:
Ethreat_displacement.query("_merge=='left_only'")

,Countries,Food Risk Score,Natural Disasters Score,Rapid Population Growth Score,Water Risk Score,Year,Conflict Stock Displacement,Conflict Internal Displacements,Disaster Internal Displacements,Disaster Stock Displacement,_merge
2,Republic of the Congo,5.0,5.0,5.0,5.0,NaN,NaN,NaN,NaN,NaN,left_only
15,Democratic Republic of the Congo,5.0,4.0,5.0,5.0,NaN,NaN,NaN,NaN,NaN,left_only
16,Comoros,4.0,5.0,5.0,5.0,NaN,NaN,NaN,NaN,NaN,left_only
17,The Gambia,4.0,5.0,5.0,5.0,NaN,NaN,NaN,NaN,NaN,left_only
18,Guinea-Bissau,5.0,4.0,5.0,5.0,NaN,NaN,NaN,NaN,NaN,left_only
...,...,...,...,...,...,...,...,...,...,...,...
219,Svalbard & Jan Mayen,2.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,left_only
220,San Marino,2.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,left_only
221,St. Pierre & Miquelon,1.0,1.0,1.0,2.0,NaN,NaN,NaN,NaN,NaN,left_only
226,Malta,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,left_only
227,Singapore,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,left_only

In [232]:
Ethreat_displacement.query("_merge=='right_only'")

,Countries,Food Risk Score,Natural Disasters Score,Rapid Population Growth Score,Water Risk Score,Year,Conflict Stock Displacement,Conflict Internal Displacements,Disaster Internal Displacements,Disaster Stock Displacement,_merge
228,Abyei Area,NaN,NaN,NaN,NaN,2022.0,56000.0,56000.0,29000.0,NaN,right_only
229,Côte d'Ivoire,NaN,NaN,NaN,NaN,2022.0,302000.0,NaN,2500.0,NaN,right_only
230,Dem. Rep. Congo,NaN,NaN,NaN,NaN,2022.0,5686000.0,4004000.0,423000.0,283000.0,right_only
231,Congo,NaN,NaN,NaN,NaN,2022.0,27000.0,NaN,42000.0,201000.0,right_only
232,Gambia,NaN,NaN,NaN,NaN,2022.0,5600.0,7800.0,7000.0,NaN,right_only
233,"Hong Kong, China",NaN,NaN,NaN,NaN,2022.0,NaN,NaN,330.0,NaN,right_only
234,Kyrgyzstan,NaN,NaN,NaN,NaN,2022.0,4000.0,166000.0,1700.0,4.0,right_only
235,Korea,NaN,NaN,NaN,NaN,2022.0,NaN,NaN,30000.0,5100.0,right_only
236,Lao PDR,NaN,NaN,NaN,NaN,2022.0,NaN,NaN,560.0,560.0,right_only
237,St. Lucia,NaN,NaN,NaN,NaN,2022.0,NaN,NaN,560.0,NaN,right_only
238,Maldives,NaN,NaN,NaN,NaN,2022.0,NaN,NaN,370.0,NaN,right_only
239,Dem. People's Rep. Korea,NaN,NaN,NaN,NaN,2022.0,NaN,NaN,200.0,NaN,right_only
240,São Tomé and Principe,NaN,NaN,NaN,NaN,2022.0,NaN,NaN,240.0,NaN,right_only
241,Türkiye,NaN,NaN,NaN,NaN,2022.0,1099000.0,NaN,6900.0,52.0,right_only
242,"Taiwan, China",NaN,NaN,NaN,NaN,2022.0,NaN,NaN,1700.0,NaN,right_only
243,United States,NaN,NaN,NaN,NaN,2022.0,NaN,NaN,675000.0,543000.0,right_only
244,St. Vincent and the Grenadines,NaN,NaN,NaN,NaN,2022.0,NaN,NaN,3.0,3.0,right_only
245,Viet Nam,NaN,NaN,NaN,NaN,2022.0,NaN,NaN,353000.0,2200.0,right_only

In [231]:
Ethreat_displacement['Countries'][Ethreat_displacement['_merge']=='both'].unique()

array(['Burundi', 'Central African Republic', 'Kenya', 'Mozambique',
       'Malawi', 'Niger', 'Somalia', 'South Sudan', 'Chad', 'Uganda',
       'Yemen', 'Afghanistan', 'Benin', 'Cameroon', 'Nigeria', 'Zimbabwe',
       'Angola', 'Ethiopia', 'Guinea', 'Haiti', 'Iraq', 'Madagascar',
       'Mauritania', 'Rwanda', 'Sudan', 'Senegal', 'Sierra Leone',
       'Tanzania', 'Zambia', 'Burkina Faso', 'Ecuador', 'Ghana',
       'Guatemala', 'Cambodia', 'Mali', 'Philippines', 'Solomon Islands',
       'Syria', 'Togo', 'Tajikistan', 'Venezuela', 'Djibouti', 'Honduras',
       'Libya', 'Myanmar', 'Mayotte', 'Nepal', 'Pakistan', 'Peru',
       'Papua New Guinea', 'Belize', 'Bolivia', 'Dominican Republic',
       'Morocco', 'Mongolia', 'Nicaragua', 'Eswatini', 'Vanuatu',
       'Indonesia', 'Sri Lanka', 'El Salvador',
       'Turks and Caicos Islands', 'Colombia', 'Cuba', 'Algeria', 'Iran',
       'Mauritius', 'New Caledonia', 'Panama', 'Suriname', 'Tonga',
       'South Africa', 'Brazil', 'Fiji', 'Georgia', 'Guyana', 'India',
       'Malaysia', 'Palestine', 'Russia', 'Thailand', 'Samoa',
       'Bangladesh', 'Kazakhstan', 'Puerto Rico', 'Romania', 'Uruguay',
       'Argentina', 'Australia', 'Costa Rica', 'Mexico',
       'North Macedonia', 'French Polynesia', 'Trinidad and Tobago',
       'Tunisia', 'Albania', 'Azerbaijan', 'China', 'Israel',
       'New Zealand', 'Oman', 'Ukraine', 'Uzbekistan', 'Armenia',
       'Canada', 'Chile', 'Croatia', 'Japan', 'Lebanon', 'Slovenia',
       'Bulgaria', 'Guadeloupe', 'Greece', 'Norway', 'Serbia',
       'Switzerland', 'Kuwait', 'Marshall Islands', 'Portugal',
       'American Samoa', 'Cook Islands', 'Ireland', 'Spain', 'Italy',
       'Bosnia and Herzegovina', 'Latvia', 'Belgium', 'Cyprus', 'Germany',
       'Finland', 'France', 'Kosovo', 'Denmark', 'United Kingdom',
       'Iceland'], dtype=object)

In [ ]:
Secondproject['_merge'].value_counts() #.plot(kind='barh')
Secondproject['Countries_and_areas'][Secondproject['_merge']=='left_only']
Secondproject['Countries_and_areas'][Secondproject['_merge']=='right_only']

Series([], Name: Countries_and_areas, dtype: object)

In [ ]:
pd.crosstab(Secondproject["Countries_and_areas"],merged["_merge"])

_merge                    both
Countries_and_areas
Albania                      1
Angola                       1
Azerbaijan                   1
Bangladesh                   1
Brazil                       1
Burkina Faso                 1
Burundi                      1
Central African Republic     1
Chad                         1
Chile                        1
Croatia                      1
El Salvador                  1
Fiji                         1
Finland                      1
France                       1
French Polynesia             1
Georgia                      1
Ghana                        1
Greece                       1
Guatemala                    1
Guinea                       1
Guyana                       1
Haiti                        1
India                        1
Iran                         1
Ireland                      1
Italy                        1
Latvia                       1
Libya                        1
Madagascar                   1
Malawi                       1
Mali                         1
Marshall Islands             1
Mauritania                   1
Mauritius                    1
Mayotte                      1
Mexico                       1
Morocco                      1
New Caledonia                1
New Zealand                  1
Nicaragua                    1
Nigeria                      1
North Macedonia              1
Oman                         1
Palestine                    1
Papua New Guinea             1
Peru                         1
Philippines                  1
Portugal                     1
Samoa                        1
Slovenia                     1
Spain                        1
Suriname                     1
Syria                        1
Tajikistan                   1
Togo                         1
Trinidad and Tobago          1
Turks and Caicos Islands     1
Venezuela                    1
Zambia                       1

In [ ]:
Secondproject.fillna('') #just some data cleaning removing the "NaN" values

,Countries_and_areas,Food Risk Score,Natural Disasters Score,Rapid Population Growth Score,Water Risk Score,Year,Conflict Stock Displacement,Conflict Internal Displacements,Disaster Internal Displacements,Disaster Stock Displacement,_merge
0,Burundi,5,5,5,5,2022,8500.0,600.0,13000.0,67000.0,both
1,Central African Republic,5,5,5,5,2022,516000.0,290000.0,77000.0,,both
2,Kenya,5,5,5,5,2022,30000.0,15000.0,318000.0,373000.0,both
3,Mozambique,5,5,5,5,2022,1030000.0,283000.0,113000.0,127000.0,both
4,Malawi,5,5,5,5,2022,,,297000.0,,both
...,...,...,...,...,...,...,...,...,...,...,...
130,France,1,2,1,1,2022,,,45000.0,44.0,both
131,Kosovo,2,1,1,1,2022,16000.0,,120.0,,both
132,Denmark,1,1,1,1,2022,,,20.0,,both
133,United Kingdom,1,1,1,1,2022,,,1900.0,80.0,both
134,Iceland,1,1,1,1,2022,,,56.0,,both

In [ ]:
#third dataset for second project: indicators of World Happiness Report 2023, as happiness is correlated with the living condition of human beings.
#link:https://www.kaggle.com/datasets/ajaypalsinghlo/world-happiness-report-2023

In [ ]:
Happiness=pd.read_csv('https://github.com/shimjide123/datman/raw/main/WHR_2023.csv').head(5)

In [ ]:
Happiness.head()

,country,region,happiness_score,gdp_per_capita,social_support,healthy_life_expectancy,freedom_to_make_life_choices,generosity,perceptions_of_corruption
0,Finland,Western Europe,7.804,1.888,1.585,0.535,0.772,0.126,0.535
1,Denmark,Western Europe,7.586,1.949,1.548,0.537,0.734,0.208,0.525
2,Iceland,Western Europe,7.530,1.926,1.620,0.559,0.738,0.250,0.187
3,Israel,Middle East and North Africa,7.473,1.833,1.521,0.577,0.569,0.124,0.158
4,Netherlands,Western Europe,7.403,1.942,1.488,0.545,0.672,0.251,0.394

In [ ]:
Happiness.rename(columns={'country': 'Countries_and_areas'}, inplace=True)

In [ ]:
#let's start merging the 3rd dataset into the second project
project2nd=Happiness.merge(Secondproject, on='Countries_and_areas', how='outer')
project2nd.head()

,Countries_and_areas,region,happiness_score,gdp_per_capita,social_support,healthy_life_expectancy,freedom_to_make_life_choices,generosity,perceptions_of_corruption,Food Risk Score,Natural Disasters Score,Rapid Population Growth Score,Water Risk Score,Year,Conflict Stock Displacement,Conflict Internal Displacements,Disaster Internal Displacements,Disaster Stock Displacement,_merge
0,Finland,Western Europe,7.804,1.888,1.585,0.535,0.772,0.126,0.535,1.0,1.0,1.0,2.0,2022.0,NaN,NaN,8.0,NaN,both
1,Denmark,Western Europe,7.586,1.949,1.548,0.537,0.734,0.208,0.525,1.0,1.0,1.0,1.0,2022.0,NaN,NaN,20.0,NaN,both
2,Iceland,Western Europe,7.530,1.926,1.620,0.559,0.738,0.250,0.187,1.0,1.0,1.0,1.0,2022.0,NaN,NaN,56.0,NaN,both
3,Israel,Middle East and North Africa,7.473,1.833,1.521,0.577,0.569,0.124,0.158,1.0,3.0,4.0,2.0,2022.0,NaN,1100.0,NaN,NaN,both
4,Netherlands,Western Europe,7.403,1.942,1.488,0.545,0.672,0.251,0.394,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
project2nd['_merge'].value_counts() #.plot(kind='barh')
project2nd['Countries_and_areas'][project2nd['_merge']=='left_only']
project2nd['Countries_and_areas'][project2nd['_merge']=='right_only']

Series([], Name: Countries_and_areas, dtype: object)

In [ ]:
project2nd['_merge'].value_counts()

both          135
left_only       0
right_only      0
Name: _merge, dtype: int64

In [ ]:
project2nd.head()

,Countries_and_areas,region,happiness_score,gdp_per_capita,social_support,healthy_life_expectancy,freedom_to_make_life_choices,generosity,perceptions_of_corruption,Food Risk Score,Natural Disasters Score,Rapid Population Growth Score,Water Risk Score,Year,Conflict Stock Displacement,Conflict Internal Displacements,Disaster Internal Displacements,Disaster Stock Displacement,_merge
0,Finland,Western Europe,7.804,1.888,1.585,0.535,0.772,0.126,0.535,1.0,1.0,1.0,2.0,2022.0,NaN,NaN,8.0,NaN,both
1,Denmark,Western Europe,7.586,1.949,1.548,0.537,0.734,0.208,0.525,1.0,1.0,1.0,1.0,2022.0,NaN,NaN,20.0,NaN,both
2,Iceland,Western Europe,7.530,1.926,1.620,0.559,0.738,0.250,0.187,1.0,1.0,1.0,1.0,2022.0,NaN,NaN,56.0,NaN,both
3,Israel,Middle East and North Africa,7.473,1.833,1.521,0.577,0.569,0.124,0.158,1.0,3.0,4.0,2.0,2022.0,NaN,1100.0,NaN,NaN,both
4,Netherlands,Western Europe,7.403,1.942,1.488,0.545,0.672,0.251,0.394,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
#change the order of columns to put the column "Year" to the front
order=['Countries_and_areas',	'region','Year',	'happiness_score',	'gdp_per_capita',	'social_support',	'healthy_life_expectancy',	'freedom_to_make_life_choices',	'generosity',	'perceptions_of_corruption',	'Food Risk Score',	'Natural Disasters Score',	'Rapid Population Growth Score',	'Water Risk Score',	'Conflict Stock Displacement',	'Conflict Internal Displacements',	'Disaster Internal Displacements',	'Disaster Stock Displacement',	'_merge']

In [ ]:
pro2nd=project2nd[order]
pro2nd.head() #that is the final merged I wanna show

,Countries_and_areas,region,Year,happiness_score,gdp_per_capita,social_support,healthy_life_expectancy,freedom_to_make_life_choices,generosity,perceptions_of_corruption,Food Risk Score,Natural Disasters Score,Rapid Population Growth Score,Water Risk Score,Conflict Stock Displacement,Conflict Internal Displacements,Disaster Internal Displacements,Disaster Stock Displacement,_merge
0,Finland,Western Europe,2022.0,7.804,1.888,1.585,0.535,0.772,0.126,0.535,1.0,1.0,1.0,2.0,NaN,NaN,8.0,NaN,both
1,Denmark,Western Europe,2022.0,7.586,1.949,1.548,0.537,0.734,0.208,0.525,1.0,1.0,1.0,1.0,NaN,NaN,20.0,NaN,both
2,Iceland,Western Europe,2022.0,7.530,1.926,1.620,0.559,0.738,0.250,0.187,1.0,1.0,1.0,1.0,NaN,NaN,56.0,NaN,both
3,Israel,Middle East and North Africa,2022.0,7.473,1.833,1.521,0.577,0.569,0.124,0.158,1.0,3.0,4.0,2.0,NaN,1100.0,NaN,NaN,both
4,Netherlands,Western Europe,NaN,7.403,1.942,1.488,0.545,0.672,0.251,0.394,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
pro2nd=pro2nd.query("Year==2022 & _merge == 'both'") #subset using query
pro2nd

,Countries_and_areas,region,Year,happiness_score,gdp_per_capita,social_support,healthy_life_expectancy,freedom_to_make_life_choices,generosity,perceptions_of_corruption,Food Risk Score,Natural Disasters Score,Rapid Population Growth Score,Water Risk Score,Conflict Stock Displacement,Conflict Internal Displacements,Disaster Internal Displacements,Disaster Stock Displacement,_merge
0,Finland,Western Europe,2022.0,7.804,1.888,1.585,0.535,0.772,0.126,0.535,1.0,1.0,1.0,2.0,NaN,NaN,8.0,NaN,both
1,Denmark,Western Europe,2022.0,7.586,1.949,1.548,0.537,0.734,0.208,0.525,1.0,1.0,1.0,1.0,NaN,NaN,20.0,NaN,both
2,Iceland,Western Europe,2022.0,7.530,1.926,1.620,0.559,0.738,0.250,0.187,1.0,1.0,1.0,1.0,NaN,NaN,56.0,NaN,both
3,Israel,Middle East and North Africa,2022.0,7.473,1.833,1.521,0.577,0.569,0.124,0.158,1.0,3.0,4.0,2.0,NaN,1100.0,NaN,NaN,both
5,Burundi,NaN,2022.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,5.0,5.0,5.0,8500.0,600.0,13000.0,67000.0,both
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
131,Cyprus,NaN,2022.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2.0,1.0,1.0,246000.0,NaN,54.0,NaN,both
132,Germany,NaN,2022.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2.0,1.0,1.0,NaN,NaN,630.0,NaN,both
133,France,NaN,2022.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2.0,1.0,1.0,NaN,NaN,45000.0,44.0,both
134,Kosovo,NaN,2022.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,1.0,1.0,1.0,16000.0,NaN,120.0,NaN,both
135,United Kingdom,NaN,2022.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,1.0,NaN,NaN,1900.0,80.0,both

In [ ]:
pro2nd=pro2nd.fillna('')
pro2nd.head()

,Countries_and_areas,region,Year,happiness_score,gdp_per_capita,social_support,healthy_life_expectancy,freedom_to_make_life_choices,generosity,perceptions_of_corruption,Food Risk Score,Natural Disasters Score,Rapid Population Growth Score,Water Risk Score,Conflict Stock Displacement,Conflict Internal Displacements,Disaster Internal Displacements,Disaster Stock Displacement,_merge
0,Finland,Western Europe,2022.0,7.804,1.888,1.585,0.535,0.772,0.126,0.535,1.0,1.0,1.0,2.0,,,8.0,,both
1,Denmark,Western Europe,2022.0,7.586,1.949,1.548,0.537,0.734,0.208,0.525,1.0,1.0,1.0,1.0,,,20.0,,both
2,Iceland,Western Europe,2022.0,7.53,1.926,1.62,0.559,0.738,0.25,0.187,1.0,1.0,1.0,1.0,,,56.0,,both
3,Israel,Middle East and North Africa,2022.0,7.473,1.833,1.521,0.577,0.569,0.124,0.158,1.0,3.0,4.0,2.0,,1100.0,,,both
5,Burundi,,2022.0,,,,,,,,5.0,5.0,5.0,5.0,8500.0,600.0,13000.0,67000.0,both

In [ ]:
pro2nd=pro2nd.reset_index(drop=True)
pro2nd.head()

,Countries_and_areas,region,Year,happiness_score,gdp_per_capita,social_support,healthy_life_expectancy,freedom_to_make_life_choices,generosity,perceptions_of_corruption,Food Risk Score,Natural Disasters Score,Rapid Population Growth Score,Water Risk Score,Conflict Stock Displacement,Conflict Internal Displacements,Disaster Internal Displacements,Disaster Stock Displacement,_merge
0,Finland,Western Europe,2022.0,7.804,1.888,1.585,0.535,0.772,0.126,0.535,1.0,1.0,1.0,2.0,,,8.0,,both
1,Denmark,Western Europe,2022.0,7.586,1.949,1.548,0.537,0.734,0.208,0.525,1.0,1.0,1.0,1.0,,,20.0,,both
2,Iceland,Western Europe,2022.0,7.53,1.926,1.62,0.559,0.738,0.25,0.187,1.0,1.0,1.0,1.0,,,56.0,,both
3,Israel,Middle East and North Africa,2022.0,7.473,1.833,1.521,0.577,0.569,0.124,0.158,1.0,3.0,4.0,2.0,,1100.0,,,both
4,Burundi,,2022.0,,,,,,,,5.0,5.0,5.0,5.0,8500.0,600.0,13000.0,67000.0,both